In [2]:
import numpy as np
a = np.array([5, 5, 5, 5])
a


array([5, 5, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
# list of lists
b = np.array([[5,5,5,], [5,5,5], [5,5,5,]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
c = np.array([[10,10,10], [10,10,10], [10,10,10]])
c

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
len(a)

4

In [10]:
len(b)

3

In [11]:
len(c)

3

In [12]:
b[0]

array([5, 5, 5])

In [13]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [14]:
c[0]

array([10, 10, 10])

In [15]:
c[0:]

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
d = np.array([[5,5,5], [5,5,5]])
d

array([[5, 5, 5],
       [5, 5, 5]])

In [17]:
e = np.zeros(2)
e

array([0., 0.])

In [18]:
f = np.ones(3)
f

array([1., 1., 1.])

In [19]:
# create an empty arrary with 2 elem,ent
g = np.empty(3)
g

array([1., 1., 1.])

In [20]:
# with range of elements
h = np.arange(6)
h

array([0, 1, 2, 3, 4, 5])

In [21]:
i = np.arange(2, 20)
i

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
j = np.arange(2, 20, 2)
j

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# linerly spaced arrays
k = np.linspace(0,10,num=5) #gives use 5 num
k

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
# specific data types in array
l = np.ones(5, dtype=np.int8)
l

array([1, 1, 1, 1, 1], dtype=int8)

In [33]:
m = np.ones(3, dtype=np.float64)
m

array([1., 1., 1.])

In [35]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
# making and reshping a 3d array
n = np.arange(24).reshape(2, 3, 4)
n

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
o = np.arange(24).reshape(2, 3, 4)
o

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
b.sum(axis=0)

array([15, 15, 15])

In [53]:
data = np.array([1.0, 2.0])
data * 1.6


array([1.6, 3.2])

In [54]:
data.max()

2.0

In [55]:
data.min()

1.0

In [56]:
data.sum()

3.0